name: Dart CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Assign size label
      uses: pascalgn/size-label-action@v0.2.2
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
